name = "CAGE"
uuid = "6123d233-acec-4f8d-9a74-aa94b458fbf9"
authors = ["Ranadeep Daw"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
